In [12]:
import time
import requests
import pandas as pd

API_KEY = "RGAPI-768e19f0-bef8-4f41-a444-7480395a0299".strip()

SEA_PLATFORMS = {
    "SG2": "Singapore / Philippines / Thailand",
    "TW2": "Taiwan",
    "VN2": "Vietnam",
}

QUEUE = "RANKED_SOLO_5x5"
PLAYERS_PER_REGION = 20

In [16]:
def riot_get(url, max_retries=5):
    headers = {
        "X-Riot-Token": API_KEY,
        "Accept": "application/json",
    }

    for attempt in range(1, max_retries + 1):
        response = requests.get(
            url,
            headers=headers,
            timeout=30,
        )

        if response.status_code == 200:
            return response.json()

        if response.status_code == 429:
            retry_after = int(response.headers.get("Retry-After", 2))
            print(f"Rate limited. Waiting {retry_after} seconds...")
            time.sleep(retry_after)
            continue

        if response.status_code in {500, 502, 503, 504}:
            wait_time = attempt * 2
            print(
                f"Riot server error {response.status_code}. "
                f"Retrying in {wait_time} seconds..."
            )
            time.sleep(wait_time)
            continue

        raise RuntimeError(
            f"Request failed\n"
            f"Status: {response.status_code}\n"
            f"URL: {url}\n"
            f"Response: {response.text[:500]}"
        )

    raise RuntimeError("Maximum retries exceeded.")

In [17]:
test_url = (
    "https://sg2.api.riotgames.com"
    "/lol/league/v4/challengerleagues/by-queue/"
    "RANKED_SOLO_5x5"
)

test_data = riot_get(test_url)

test_data.keys()

dict_keys(['tier', 'queue', 'entries'])

In [18]:
sg2_entries = sorted(
    test_data["entries"],
    key=lambda player: player.get("leaguePoints", 0),
    reverse=True,
)[:20]

sg2_rows = []

for position, player in enumerate(sg2_entries, start=1):
    wins = player.get("wins", 0)
    losses = player.get("losses", 0)
    games_played = wins + losses

    sg2_rows.append({
        "platform": "SG2",
        "region": "Singapore / Philippines / Thailand",
        "position": position,
        "puuid": player.get("puuid"),
        "summoner_id": player.get("summonerId"),
        "rank": player.get("rank"),
        "league_points": player.get("leaguePoints", 0),
        "wins": wins,
        "losses": losses,
        "games_played": games_played,
        "win_rate": round(
            wins / games_played * 100,
            2,
        ) if games_played else 0,
        "hot_streak": player.get("hotStreak", False),
    })

df_sg2 = pd.DataFrame(sg2_rows)

df_sg2

,platform,region,position,puuid,summoner_id,rank,league_points,wins,losses,games_played,win_rate,hot_streak
0,SG2,Singapore / Philippines / Thailand,1,CYHXF3JglCMksGnfzOJHNP6rA_Cg-OwLJFUyY4s18TvzBb...,None,I,2706,276,155,431,64.04,False
1,SG2,Singapore / Philippines / Thailand,2,409Xdc_OYG4J-h3aJahviEJtmWqwzshfh_ct6okWzKk8vq...,None,I,2454,301,214,515,58.45,False
2,SG2,Singapore / Philippines / Thailand,3,BVIFcZB-UDTySogrrRQ_kvcedaQsoRcManQze9mAOqpj07...,None,I,2347,352,223,575,61.22,False
3,SG2,Singapore / Philippines / Thailand,4,4O1ayC5liHlnWhWENkFScM3DJLBtcpHK21Mk5jEl6aNJbI...,None,I,2229,363,303,666,54.50,False
4,SG2,Singapore / Philippines / Thailand,5,SMkjn6yMBOV3Z_o3SMeUhzpLBHdikGl5xSdoJn9-3rpAWM...,None,I,2227,311,203,514,60.51,False
5,SG2,Singapore / Philippines / Thailand,6,GPI98qiQNFstOjtbdEbO_fNyQlyauHeDxhKn_YENRaro_W...,None,I,2218,222,130,352,63.07,False
6,SG2,Singapore / Philippines / Thailand,7,KnwS2ySfEsEE7YQY9Rx1PFAW3TPz0vRAlLAAAHg2uSNUyb...,None,I,2187,280,201,481,58.21,False
7,SG2,Singapore / Philippines / Thailand,8,8rYP8gp8kuvsHqnfSHI-wuJEcJ_I1LoNhPefG8tazZ0wuC...,None,I,2039,147,74,221,66.52,False
8,SG2,Singapore / Philippines / Thailand,9,yLinrXmSSmuqHENHp7B5EudNw_c27SASN12cNvWrwA6LQF...,None,I,2005,310,254,564,54.96,False
9,SG2,Singapore / Philippines / Thailand,10,kkH8RQf5_yoLIt11fKlu5VX2yZIIZTJKMv7RvTFv6gYW27...,None,I,2005,269,207,476,56.51,False
10,SG2,Singapore / Philippines / Thailand,11,QjMmYfpjGLuCRs4OAHU7woZX2dScnledNek4LONmrREgdk...,None,I,1985,348,199,547,63.62,False
11,SG2,Singapore / Philippines / Thailand,12,WJFRYpwm7jl6lFPKEKHiPUPzMD0rqaKAgdtlIe5xMRYvNH...,None,I,1967,438,372,810,54.07,False
12,SG2,Singapore / Philippines / Thailand,13,6oJ_MVkY5kzTkXzsrqZp4ODnB9wtg0QcP3bSdmKwV3tw7-...,None,I,1937,177,123,300,59.00,True
13,SG2,Singapore / Philippines / Thailand,14,7HgGRQoZ5zkwYWGVvUJ1jvdeK-YuHJ11Edjw2fLB-e6pvx...,None,I,1925,156,105,261,59.77,False
14,SG2,Singapore / Philippines / Thailand,15,QRsEjFfOIoq4LPM9ez1E2FaLBy6ncS-kwVTPm0SdsqZPHe...,None,I,1864,194,133,327,59.33,True
15,SG2,Singapore / Philippines / Thailand,16,GPsSIMc5eUE9DI0GDD7orwWdRizMOep114PIU8tDz35yer...,None,I,1822,168,129,297,56.57,False
16,SG2,Singapore / Philippines / Thailand,17,PCJV7pqspXhFQkKu5C7X0iB9X_eeU9T2Ty1D2YbhyGcXWY...,None,I,1798,165,117,282,58.51,False
17,SG2,Singapore / Philippines / Thailand,18,R9cOQwHLtR4qw-Xh_dLOC2cejU8zs-Fv7hcgJnwuwztM8I...,None,I,1775,237,187,424,55.90,False
18,SG2,Singapore / Philippines / Thailand,19,Q-SIPNwo7mpViYQ3YKt_PeMouRxuhSJxmBoLPad6xPG1w1...,None,I,1661,200,149,349,57.31,True
19,SG2,Singapore / Philippines / Thailand,20,Kv4ZX1o5oG_OlLrjxZO3jCUp8Fm4plCr_B25n2hlNm_mCm...,None,I,1576,150,90,240,62.50,False

In [21]:
def get_top_players(platform, region_name, limit=20):
    url = (
        f"https://{platform.lower()}.api.riotgames.com"
        f"/lol/league/v4/challengerleagues/by-queue/{QUEUE}"
    )

    leaderboard = riot_get(url)

    entries = sorted(
        leaderboard.get("entries", []),
        key=lambda player: player.get("leaguePoints", 0),
        reverse=True,
    )[:limit]

    rows = []

    for position, player in enumerate(entries, start=1):
        wins = player.get("wins", 0)
        losses = player.get("losses", 0)
        games_played = wins + losses

        rows.append({
            "platform": platform,
            "region": region_name,
            "position": position,
            "puuid": player.get("puuid"),
            "summoner_id": player.get("summonerId"),
            "tier": leaderboard.get("tier"),
            "rank": player.get("rank"),
            "league_points": player.get("leaguePoints", 0),
            "wins": wins,
            "losses": losses,
            "games_played": games_played,
            "win_rate": round(
                wins / games_played * 100,
                2,
            ) if games_played else 0,
            "hot_streak": player.get("hotStreak", False),
        })

    return rows

all_players = []

for platform, region_name in SEA_PLATFORMS.items():
    print(f"Calling {platform}...")

    region_players = get_top_players(
        platform=platform,
        region_name=region_name,
        limit=PLAYERS_PER_REGION,
    )

    all_players.extend(region_players)

df = pd.DataFrame(all_players)


pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 50)

df[
    [
        "platform",
        "position",
        "puuid",
        "league_points",
        "wins",
        "losses",
        "games_played",
        "win_rate",
    ]
]

Calling SG2...
Calling TW2...
Calling VN2...

,platform,position,puuid,league_points,wins,losses,games_played,win_rate
0,SG2,1,CYHXF3JglCMksGnfzOJHNP6rA_Cg-OwLJFUyY4s18TvzBb...,2706,276,155,431,64.04
1,SG2,2,409Xdc_OYG4J-h3aJahviEJtmWqwzshfh_ct6okWzKk8vq...,2454,301,214,515,58.45
2,SG2,3,BVIFcZB-UDTySogrrRQ_kvcedaQsoRcManQze9mAOqpj07...,2347,352,223,575,61.22
3,SG2,4,4O1ayC5liHlnWhWENkFScM3DJLBtcpHK21Mk5jEl6aNJbI...,2229,363,303,666,54.50
4,SG2,5,SMkjn6yMBOV3Z_o3SMeUhzpLBHdikGl5xSdoJn9-3rpAWM...,2227,311,203,514,60.51
5,SG2,6,GPI98qiQNFstOjtbdEbO_fNyQlyauHeDxhKn_YENRaro_W...,2218,222,130,352,63.07
6,SG2,7,KnwS2ySfEsEE7YQY9Rx1PFAW3TPz0vRAlLAAAHg2uSNUyb...,2187,280,201,481,58.21
7,SG2,8,8rYP8gp8kuvsHqnfSHI-wuJEcJ_I1LoNhPefG8tazZ0wuC...,2039,147,74,221,66.52
8,SG2,9,yLinrXmSSmuqHENHp7B5EudNw_c27SASN12cNvWrwA6LQF...,2005,310,254,564,54.96
9,SG2,10,kkH8RQf5_yoLIt11fKlu5VX2yZIIZTJKMv7RvTFv6gYW27...,2005,269,207,476,56.51
10,SG2,11,QjMmYfpjGLuCRs4OAHU7woZX2dScnledNek4LONmrREgdk...,1985,348,199,547,63.62
11,SG2,12,WJFRYpwm7jl6lFPKEKHiPUPzMD0rqaKAgdtlIe5xMRYvNH...,1967,438,372,810,54.07
12,SG2,13,6oJ_MVkY5kzTkXzsrqZp4ODnB9wtg0QcP3bSdmKwV3tw7-...,1937,177,123,300,59.00
13,SG2,14,7HgGRQoZ5zkwYWGVvUJ1jvdeK-YuHJ11Edjw2fLB-e6pvx...,1925,156,105,261,59.77
14,SG2,15,QRsEjFfOIoq4LPM9ez1E2FaLBy6ncS-kwVTPm0SdsqZPHe...,1864,194,133,327,59.33
15,SG2,16,GPsSIMc5eUE9DI0GDD7orwWdRizMOep114PIU8tDz35yer...,1822,168,129,297,56.57
16,SG2,17,PCJV7pqspXhFQkKu5C7X0iB9X_eeU9T2Ty1D2YbhyGcXWY...,1798,165,117,282,58.51
17,SG2,18,R9cOQwHLtR4qw-Xh_dLOC2cejU8zs-Fv7hcgJnwuwztM8I...,1775,237,187,424,55.90
18,SG2,19,Q-SIPNwo7mpViYQ3YKt_PeMouRxuhSJxmBoLPad6xPG1w1...,1661,200,149,349,57.31
19,SG2,20,Kv4ZX1o5oG_OlLrjxZO3jCUp8Fm4plCr_B25n2hlNm_mCm...,1576,150,90,240,62.50
20,TW2,1,kEUZFWpLqHx7qSOLAWUPrSFcbHl6Cv7o2m_G28d3oezK19...,2286,216,147,363,59.50
21,TW2,2,haqIjpIUqLD5xjx7aHaJJqLL4TMHvVgm52wc1tZzJfr0EV...,2244,143,75,218,65.60
22,TW2,3,TJtUwCsvz8JYHefREQSJY0JOxq_WQP3sTIfjxrTvtiXHTx...,2112,448,405,853,52.52
23,TW2,4,EZB-pQV69OG5Rt-g3HSOXeT3MFEUcbNNP19kjLieVl7_Ck...,2099,236,159,395,59.75
24,TW2,5,p8h8aLLzD5SHSLf8wWwjXXrqiNUp572HR7KgqSdT1CJEpY...,2044,246,193,439,56.04
25,TW2,6,13ObESU8wKC9hAbZPRK1OezqV6Fzg_w9v7Rgh0k7nhnqQ4...,2024,159,94,253,62.85
26,TW2,7,oUxEO2EGPFUppK19dMF7N70zZrCHGQp3U9unP6943vAk1L...,1947,287,214,501,57.29
27,TW2,8,5v4HPpPhUJZKv8oOgCtvKZZstV0sd-caUzT9zDtqLsgwsW...,1930,268,203,471,56.90
28,TW2,9,nUh7qmfmM-i5XZzWFGgVzHJRNRxmzvcYhPNZrX6vROC3OA...,1915,282,219,501,56.29
29,TW2,10,IUb1bRD9p_C4sYGBr6VMS1Q7Vsez4b-MD-LgaJ0xYkGINf...,1899,142,91,233,60.94
30,TW2,11,0w9PCQa3jISZVVsQzwSS81TvAR5HoNTqRWPlrca8uo7ES1...,1897,163,114,277,58.84
31,TW2,12,7XopwYoU2XftTX1M1ZLYbNgWrt_4D-0GbUdaCaMnNFwZ79...,1855,171,106,277,61.73
32,TW2,13,m-JPtbB-hfa-Z_r42Gzr41WY1IGar3wKehn77lINzCjeMW...,1829,335,257,592,56.59
33,TW2,14,mwbxcXbB0-LlZ2SfL2YdCYXcOkQgvYVgDeDe5v119XTzZ2...,1826,198,127,325,60.92
34,TW2,15,JGDS_RsygeXTsMcxodD9xajC59tZ5LhPgX2Vb670fp7I_x...,1812,239,179,418,57.18
35,TW2,16,er0JERKRV4I3bHVaaxebNgs7qdQdsd6wUEli2zGWpxxlLR...,1802,182,122,304,59.87
36,TW2,17,hfEO3NSjkob0tSe7yTKyQGLBHQPhoosABQRM_9pYTt8hLC...,1741,174,132,306,56.86
37,TW2,18,jiLGR8maozckgTXih2Z4ij1XfKX1D-VfF7stX7a6Bkd31Q...,1737,196,133,329,59.57
38,TW2,19,eIiClTf-vKqaZfgyzOkEwrhUp9K4lViU_4ilDTb3w_bGHp...,1736,127,82,209,60.77
39,TW2,20,vhnxUixMG4ctHsPECEJvAE4ZTRY2ec6SZaDeXiA5MByEGq...,1732,196,135,331,59.21
40,VN2,1,tK2U9U-ll9-nVmLH5Dqr8pcFvD7qlmKexqjdjEJLEIaSIu...,3566,496,225,721,68.79
41,VN2,2,DD71rT_k9C9xogdGoDK6G1ql70a8a0btoKc7S63cRbtXxD...,3245,297,159,456,65.13
42,VN2,3,aM1DgNvoJGLZAxmAdsmEW3_GrQdYYz-YFjkoBc79nqwvSt...,3232,327,146,473,69.13
43,VN2,4,zpsxApg-b-226weoANjiBpEw4ht6eVr6BJ_QYJ7tBY-Ijm...,3217,650,544,1194,54.44
44,VN2,5,fF3Vvm0SggJf49dBpjT8tzfDYcpv3PMz4gFkEFjs55cZe3...,3164,452,295,747,60.51
45,VN2,6,C8YkUlrji_Tjs7Zo_JlbPjUHvZmX4jIC9Rl29VkTurzGth...,3159,311,206,517,60.15
46,VN2,7,Pi8W0txMAhAjlMsHwN9tLtYp5MKshP2HA4gBwDLPQWKSU2...,3149,244,156,400,61.00
47,VN2,8,djHF0tYzdEW73l8r_VAYp4ST4PgASFABsBY64W-wCBkYiS...,2797,341,241,582,58.59
48,VN2,9,H5RVGuCeE47Px81wZ8dm8h352ArZsQimK5y6XoaoQ-bFUE...,2769,521,435,956,54.50
49,VN2,10,yAN8Pt3fg8cl2pvYGuyBHCaetRiFjQli93ID0CeokIUrW-...,2728,591,482,1073,55.08
50,VN2,11,yHGOAEBsZdZJvTzoLDouHwfWIoUZs_z6HGrHiWCne7DnS_...,2705,200,115,315,63.49
51,VN2,12,APKc3Pv3TfK3haF6Y-eLJ3DVoZwURc77KTpVFC8OwI48rh...,2702,159,74,233,68.24
52,VN2,13,NBDFG859O-RPQV39MT4zVNDEOCpEXsI8TxXbRLjOLddlrv...,2688,270,154,424,63.68
53,VN2,14,eJUjaIvax7cQTn80LrvgcUzni-KDi_Ca1RnxvXI0xUwMIn...,2651,246,156,402,61.19
54,VN2,15,NI4lfXKVZ9SykKuViOj2zU82fgVH4s_W9bxhK5owm4TkGw...,2594,1482,1403,2885,51.37
55,VN2,16,8kpSDvHGta4T0YwnRUbI5uHUHKoq7Zp7Z1D26AL_I_XVhI...,2585,241,147,388,62.11
56,VN2,17,aH72BPgtKUUJ_UfAyhib-sMzEgQ7FOdfJmo2P3-54Gh9zI...,2517,576,500,1076,53.53
57,VN2,18,EIT_-Zupfvn0pZPMN9_yuPvLtQ8gFrNUFUF99LolzAMKDu...,2500,291,237,528,55.11
58,VN2,19,bHzrFr9poZf8GoRev9pzHH2nA4OisDt6I2LAvhCXsxJ1qn...,2482,249,203,452,55.09
59,VN2,20,EYQM_2hSwaRGrDUWXR9eV__YT3UGsdi54sN6hKlnSfTqwp...,2477,415,317,732,56.69

In [23]:
player = requests.get(
    "https://asia.api.riotgames.com/riot/account/v1/accounts/by-riot-id/burberry/5234",
    headers={"X-Riot-Token": API_KEY}
).json()

player

{'puuid': 'DLDP5bWITVDgoXEGAKjd6oQbgZ1_wWSGbQQkK2YLISUS4LR7iCxWHAeIuyBBObMuuGbnoELCou_oxw',
 'gameName': 'burberry',
 'tagLine': '5234'}